/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev */

#ifndef PB_HELIUM_TXNS_TXN_POC_RECEIPTS_V1_PB_H_INCLUDED
#define PB_HELIUM_TXNS_TXN_POC_RECEIPTS_V1_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _helium_txns_origin {
    helium_txns_origin_p2p = 0,
    helium_txns_origin_radio = 1
} helium_txns_origin;
#define _helium_txns_origin_MIN helium_txns_origin_p2p
#define _helium_txns_origin_MAX helium_txns_origin_radio
#define _helium_txns_origin_ARRAYSIZE ((helium_txns_origin)(helium_txns_origin_radio+1))

/* Struct definitions */
typedef struct _helium_txns_poc_receipt_v1 {
    pb_callback_t gateway;
    uint64_t timestamp;
    int32_t signal;
    pb_callback_t data;
    helium_txns_origin origin;
    pb_callback_t signature;
/* @@protoc_insertion_point(struct:helium_txns_poc_receipt_v1) */
} helium_txns_poc_receipt_v1;


typedef struct _helium_txns_poc_witness_v1 {
    pb_callback_t gateway;
    uint64_t timestamp;
    int32_t signal;
    pb_callback_t packet_hash;
    pb_callback_t signature;
/* @@protoc_insertion_point(struct:helium_txns_poc_witness_v1) */
} helium_txns_poc_witness_v1;


typedef struct _helium_txns_txn_poc_receipts_v1 {
    pb_callback_t challenger;
    pb_callback_t secret;
    pb_callback_t onion_key_hash;
    pb_callback_t path;
    uint64_t fee;
    pb_callback_t signature;
/* @@protoc_insertion_point(struct:helium_txns_txn_poc_receipts_v1) */
} helium_txns_txn_poc_receipts_v1;


typedef struct _helium_txns_poc_path_element_v1 {
    pb_callback_t challengee;
    bool has_receipt;
    helium_txns_poc_receipt_v1 receipt;
    pb_callback_t witnesses;
/* @@protoc_insertion_point(struct:helium_txns_poc_path_element_v1) */
} helium_txns_poc_path_element_v1;


typedef struct _helium_txns_poc_response_v1 {
    pb_size_t which_payload;
    union {
        helium_txns_poc_receipt_v1 receipt;
        helium_txns_poc_witness_v1 witness;
    } payload;
/* @@protoc_insertion_point(struct:helium_txns_poc_response_v1) */
} helium_txns_poc_response_v1;


/* Initializer values for message structs */
#define helium_txns_poc_receipt_v1_init_default  {{{NULL}, NULL}, 0, 0, {{NULL}, NULL}, _helium_txns_origin_MIN, {{NULL}, NULL}}
#define helium_txns_poc_witness_v1_init_default  {{{NULL}, NULL}, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define helium_txns_poc_response_v1_init_default {0, {helium_txns_poc_receipt_v1_init_default}}
#define helium_txns_poc_path_element_v1_init_default {{{NULL}, NULL}, false, helium_txns_poc_receipt_v1_init_default, {{NULL}, NULL}}
#define helium_txns_txn_poc_receipts_v1_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}}
#define helium_txns_poc_receipt_v1_init_zero     {{{NULL}, NULL}, 0, 0, {{NULL}, NULL}, _helium_txns_origin_MIN, {{NULL}, NULL}}
#define helium_txns_poc_witness_v1_init_zero     {{{NULL}, NULL}, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define helium_txns_poc_response_v1_init_zero    {0, {helium_txns_poc_receipt_v1_init_zero}}
#define helium_txns_poc_path_element_v1_init_zero {{{NULL}, NULL}, false, helium_txns_poc_receipt_v1_init_zero, {{NULL}, NULL}}
#define helium_txns_txn_poc_receipts_v1_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define helium_txns_poc_receipt_v1_gateway_tag   1
#define helium_txns_poc_receipt_v1_timestamp_tag 2
#define helium_txns_poc_receipt_v1_signal_tag    3
#define helium_txns_poc_receipt_v1_data_tag      4
#define helium_txns_poc_receipt_v1_origin_tag    5
#define helium_txns_poc_receipt_v1_signature_tag 6
#define helium_txns_poc_witness_v1_gateway_tag   1
#define helium_txns_poc_witness_v1_timestamp_tag 2
#define helium_txns_poc_witness_v1_signal_tag    3
#define helium_txns_poc_witness_v1_packet_hash_tag 4
#define helium_txns_poc_witness_v1_signature_tag 5
#define helium_txns_txn_poc_receipts_v1_challenger_tag 1
#define helium_txns_txn_poc_receipts_v1_secret_tag 2
#define helium_txns_txn_poc_receipts_v1_onion_key_hash_tag 3
#define helium_txns_txn_poc_receipts_v1_path_tag 4
#define helium_txns_txn_poc_receipts_v1_fee_tag  5
#define helium_txns_txn_poc_receipts_v1_signature_tag 6
#define helium_txns_poc_path_element_v1_challengee_tag 1
#define helium_txns_poc_path_element_v1_receipt_tag 2
#define helium_txns_poc_path_element_v1_witnesses_tag 3
#define helium_txns_poc_response_v1_receipt_tag  1
#define helium_txns_poc_response_v1_witness_tag  2

/* Struct field encoding specification for nanopb */
#define helium_txns_poc_receipt_v1_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES, gateway, 1) \
X(a, STATIC, SINGULAR, UINT64, timestamp, 2) \
X(a, STATIC, SINGULAR, SINT32, signal, 3) \
X(a, CALLBACK, SINGULAR, BYTES, data, 4) \
X(a, STATIC, SINGULAR, UENUM, origin, 5) \
X(a, CALLBACK, SINGULAR, BYTES, signature, 6)
#define helium_txns_poc_receipt_v1_CALLBACK pb_default_field_callback
#define helium_txns_poc_receipt_v1_DEFAULT NULL

#define helium_txns_poc_witness_v1_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES, gateway, 1) \
X(a, STATIC, SINGULAR, UINT64, timestamp, 2) \
X(a, STATIC, SINGULAR, SINT32, signal, 3) \
X(a, CALLBACK, SINGULAR, BYTES, packet_hash, 4) \
X(a, CALLBACK, SINGULAR, BYTES, signature, 5)
#define helium_txns_poc_witness_v1_CALLBACK pb_default_field_callback
#define helium_txns_poc_witness_v1_DEFAULT NULL

#define helium_txns_poc_response_v1_FIELDLIST(X, a) \
X(a, STATIC, ONEOF, MESSAGE, (payload,receipt,payload.receipt), 1) \
X(a, STATIC, ONEOF, MESSAGE, (payload,witness,payload.witness), 2)
#define helium_txns_poc_response_v1_CALLBACK NULL
#define helium_txns_poc_response_v1_DEFAULT NULL
#define helium_txns_poc_response_v1_payload_receipt_MSGTYPE helium_txns_poc_receipt_v1
#define helium_txns_poc_response_v1_payload_witness_MSGTYPE helium_txns_poc_witness_v1

#define helium_txns_poc_path_element_v1_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES, challengee, 1) \
X(a, STATIC, OPTIONAL, MESSAGE, receipt, 2) \
X(a, CALLBACK, REPEATED, MESSAGE, witnesses, 3)
#define helium_txns_poc_path_element_v1_CALLBACK pb_default_field_callback
#define helium_txns_poc_path_element_v1_DEFAULT NULL
#define helium_txns_poc_path_element_v1_receipt_MSGTYPE helium_txns_poc_receipt_v1
#define helium_txns_poc_path_element_v1_witnesses_MSGTYPE helium_txns_poc_witness_v1

#define helium_txns_txn_poc_receipts_v1_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES, challenger, 1) \
X(a, CALLBACK, SINGULAR, BYTES, secret, 2) \
X(a, CALLBACK, SINGULAR, BYTES, onion_key_hash, 3) \
X(a, CALLBACK, REPEATED, MESSAGE, path, 4) \
X(a, STATIC, SINGULAR, UINT64, fee, 5) \
X(a, CALLBACK, SINGULAR, BYTES, signature, 6)
#define helium_txns_txn_poc_receipts_v1_CALLBACK pb_default_field_callback
#define helium_txns_txn_poc_receipts_v1_DEFAULT NULL
#define helium_txns_txn_poc_receipts_v1_path_MSGTYPE helium_txns_poc_path_element_v1

extern const pb_msgdesc_t helium_txns_poc_receipt_v1_msg;
extern const pb_msgdesc_t helium_txns_poc_witness_v1_msg;
extern const pb_msgdesc_t helium_txns_poc_response_v1_msg;
extern const pb_msgdesc_t helium_txns_poc_path_element_v1_msg;
extern const pb_msgdesc_t helium_txns_txn_poc_receipts_v1_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define helium_txns_poc_receipt_v1_fields &helium_txns_poc_receipt_v1_msg
#define helium_txns_poc_witness_v1_fields &helium_txns_poc_witness_v1_msg
#define helium_txns_poc_response_v1_fields &helium_txns_poc_response_v1_msg
#define helium_txns_poc_path_element_v1_fields &helium_txns_poc_path_element_v1_msg
#define helium_txns_txn_poc_receipts_v1_fields &helium_txns_txn_poc_receipts_v1_msg

/* Maximum encoded size of messages (where known) */
/* helium_txns_poc_receipt_v1_size depends on runtime parameters */
/* helium_txns_poc_witness_v1_size depends on runtime parameters */
/* helium_txns_poc_response_v1_size depends on runtime parameters */
/* helium_txns_poc_path_element_v1_size depends on runtime parameters */
/* helium_txns_txn_poc_receipts_v1_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
