#!/usr/bin/env bash
docker_tag=73c9e07
docker_image_base=ledger-app-builder
docker_image="${docker_image_base}:${docker_tag}"

if ! docker image inspect "$docker_image" &>/dev/null; then
  echo "docker image \`$docker_image\` not found. please see README.md" 1>&2
  exit 1
fi

here="$(readlink -f "$(dirname "$0")")"
user=$(id -u)
group=$(id -g)
owner="$user:$group"
docker run --rm -t -v "$here:/app" "ledger-app-builder:$docker_tag" /bin/bash -c "make ${*}; chown -fR $owner /app/{bin,debug,dep,libsol/target,obj,src/glyphs.{c,h}}"
