/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev */

#ifndef PB_HELIUM_TXNS_TXN_POC_REQUEST_V1_PB_H_INCLUDED
#define PB_HELIUM_TXNS_TXN_POC_REQUEST_V1_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _helium_txns_txn_poc_request_v1 {
    pb_callback_t challenger;
    pb_callback_t secret_hash;
    pb_callback_t onion_key_hash;
    pb_callback_t block_hash;
    uint64_t fee;
    pb_callback_t signature;
    uint32_t version;
/* @@protoc_insertion_point(struct:helium_txns_txn_poc_request_v1) */
} helium_txns_txn_poc_request_v1;


/* Initializer values for message structs */
#define helium_txns_txn_poc_request_v1_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0}
#define helium_txns_txn_poc_request_v1_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define helium_txns_txn_poc_request_v1_challenger_tag 1
#define helium_txns_txn_poc_request_v1_secret_hash_tag 2
#define helium_txns_txn_poc_request_v1_onion_key_hash_tag 3
#define helium_txns_txn_poc_request_v1_block_hash_tag 4
#define helium_txns_txn_poc_request_v1_fee_tag   5
#define helium_txns_txn_poc_request_v1_signature_tag 6
#define helium_txns_txn_poc_request_v1_version_tag 7

/* Struct field encoding specification for nanopb */
#define helium_txns_txn_poc_request_v1_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES, challenger, 1) \
X(a, CALLBACK, SINGULAR, BYTES, secret_hash, 2) \
X(a, CALLBACK, SINGULAR, BYTES, onion_key_hash, 3) \
X(a, CALLBACK, SINGULAR, BYTES, block_hash, 4) \
X(a, STATIC, SINGULAR, UINT64, fee, 5) \
X(a, CALLBACK, SINGULAR, BYTES, signature, 6) \
X(a, STATIC, SINGULAR, UINT32, version, 7)
#define helium_txns_txn_poc_request_v1_CALLBACK pb_default_field_callback
#define helium_txns_txn_poc_request_v1_DEFAULT NULL

extern const pb_msgdesc_t helium_txns_txn_poc_request_v1_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define helium_txns_txn_poc_request_v1_fields &helium_txns_txn_poc_request_v1_msg

/* Maximum encoded size of messages (where known) */
/* helium_txns_txn_poc_request_v1_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
