/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev */

#ifndef PB_HELIUM_TXNS_TXN_STATE_CHANNEL_CLOSE_V1_PB_H_INCLUDED
#define PB_HELIUM_TXNS_TXN_STATE_CHANNEL_CLOSE_V1_PB_H_INCLUDED
#include <pb.h>

#include "state_channel/state_channel_v1.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _helium_txns_txn_state_channel_close_v1 {
    bool has_state_channel;
    state_channel_v1 state_channel;
    pb_callback_t closer;
    pb_callback_t signature;
/* @@protoc_insertion_point(struct:helium_txns_txn_state_channel_close_v1) */
} helium_txns_txn_state_channel_close_v1;


/* Initializer values for message structs */
#define helium_txns_txn_state_channel_close_v1_init_default {false, state_channel_v1_init_default, {{NULL}, NULL}, {{NULL}, NULL}}
#define helium_txns_txn_state_channel_close_v1_init_zero {false, state_channel_v1_init_zero, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define helium_txns_txn_state_channel_close_v1_state_channel_tag 1
#define helium_txns_txn_state_channel_close_v1_closer_tag 2
#define helium_txns_txn_state_channel_close_v1_signature_tag 3

/* Struct field encoding specification for nanopb */
#define helium_txns_txn_state_channel_close_v1_FIELDLIST(X, a) \
X(a, STATIC, OPTIONAL, MESSAGE, state_channel, 1) \
X(a, CALLBACK, SINGULAR, BYTES, closer, 2) \
X(a, CALLBACK, SINGULAR, BYTES, signature, 3)
#define helium_txns_txn_state_channel_close_v1_CALLBACK pb_default_field_callback
#define helium_txns_txn_state_channel_close_v1_DEFAULT NULL
#define helium_txns_txn_state_channel_close_v1_state_channel_MSGTYPE state_channel_v1

extern const pb_msgdesc_t helium_txns_txn_state_channel_close_v1_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define helium_txns_txn_state_channel_close_v1_fields &helium_txns_txn_state_channel_close_v1_msg

/* Maximum encoded size of messages (where known) */
/* helium_txns_txn_state_channel_close_v1_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
