/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "blockchain_sync_handler.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(blockchain_sync_hash, blockchain_sync_hash, AUTO)


PB_BIND(blockchain_sync_blocks, blockchain_sync_blocks, AUTO)


PB_BIND(blockchain_sync_req, blockchain_sync_req, AUTO)



