/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "blockchain_state_channel_v1.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(helium_blockchain_state_channel_summary_v1, helium_blockchain_state_channel_summary_v1, AUTO)


PB_BIND(helium_blockchain_state_channel_v1, helium_blockchain_state_channel_v1, AUTO)


PB_BIND(helium_blockchain_state_channel_response_v1, helium_blockchain_state_channel_response_v1, AUTO)


PB_BIND(helium_blockchain_state_channel_packet_v1, helium_blockchain_state_channel_packet_v1, AUTO)


PB_BIND(helium_blockchain_state_channel_offer_v1, helium_blockchain_state_channel_offer_v1, AUTO)


PB_BIND(helium_blockchain_state_channel_purchase_v1, helium_blockchain_state_channel_purchase_v1, AUTO)


PB_BIND(helium_blockchain_state_channel_diff_v1, helium_blockchain_state_channel_diff_v1, AUTO)


PB_BIND(helium_blockchain_state_channel_diff_entry_v1, helium_blockchain_state_channel_diff_entry_v1, AUTO)


PB_BIND(helium_blockchain_state_channel_diff_append_summary_v1, helium_blockchain_state_channel_diff_append_summary_v1, AUTO)


PB_BIND(helium_blockchain_state_channel_diff_update_summary_v1, helium_blockchain_state_channel_diff_update_summary_v1, AUTO)


PB_BIND(helium_blockchain_state_channel_banner_v1, helium_blockchain_state_channel_banner_v1, AUTO)


PB_BIND(helium_blockchain_state_channel_rejection_v1, helium_blockchain_state_channel_rejection_v1, AUTO)


PB_BIND(helium_blockchain_state_channel_message_v1, helium_blockchain_state_channel_message_v1, AUTO)




