/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_HELIUM_BLOCKCHAIN_LEDGER_SUBNETWORK_V1_PB_H_INCLUDED
#define PB_HELIUM_BLOCKCHAIN_LEDGER_SUBNETWORK_V1_PB_H_INCLUDED
#include <pb.h>
#include "blockchain_token_type_v1.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _helium_blockchain_ledger_subnetwork_v1 { 
    helium_blockchain_token_type_v1 type; 
    uint64_t token_treasury; 
    uint64_t hnt_treasury; 
    pb_callback_t subnetwork_key; 
    pb_callback_t reward_server_keys; 
    /* this nonce is updated by the update_subnetwork transaction */
    uint64_t nonce; 
    uint64_t last_rewarded_block; 
} helium_blockchain_ledger_subnetwork_v1;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define helium_blockchain_ledger_subnetwork_v1_init_default {_helium_blockchain_token_type_v1_MIN, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0}
#define helium_blockchain_ledger_subnetwork_v1_init_zero {_helium_blockchain_token_type_v1_MIN, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define helium_blockchain_ledger_subnetwork_v1_type_tag 1
#define helium_blockchain_ledger_subnetwork_v1_token_treasury_tag 2
#define helium_blockchain_ledger_subnetwork_v1_hnt_treasury_tag 3
#define helium_blockchain_ledger_subnetwork_v1_subnetwork_key_tag 4
#define helium_blockchain_ledger_subnetwork_v1_reward_server_keys_tag 5
#define helium_blockchain_ledger_subnetwork_v1_nonce_tag 6
#define helium_blockchain_ledger_subnetwork_v1_last_rewarded_block_tag 7

/* Struct field encoding specification for nanopb */
#define helium_blockchain_ledger_subnetwork_v1_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, UINT64,   token_treasury,    2) \
X(a, STATIC,   SINGULAR, UINT64,   hnt_treasury,      3) \
X(a, CALLBACK, SINGULAR, BYTES,    subnetwork_key,    4) \
X(a, CALLBACK, REPEATED, BYTES,    reward_server_keys,   5) \
X(a, STATIC,   SINGULAR, UINT64,   nonce,             6) \
X(a, STATIC,   SINGULAR, UINT64,   last_rewarded_block,   7)
#define helium_blockchain_ledger_subnetwork_v1_CALLBACK pb_default_field_callback
#define helium_blockchain_ledger_subnetwork_v1_DEFAULT NULL

extern const pb_msgdesc_t helium_blockchain_ledger_subnetwork_v1_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define helium_blockchain_ledger_subnetwork_v1_fields &helium_blockchain_ledger_subnetwork_v1_msg

/* Maximum encoded size of messages (where known) */
/* helium_blockchain_ledger_subnetwork_v1_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
