/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_HELIUM_BLOCKCHAIN_TXN_POC_RECEIPTS_V2_PB_H_INCLUDED
#define PB_HELIUM_BLOCKCHAIN_TXN_POC_RECEIPTS_V2_PB_H_INCLUDED
#include <pb.h>
#include "blockchain_poc_core_v1.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _helium_blockchain_txn_poc_receipts_v2 { 
    pb_callback_t challenger; 
    pb_callback_t secret; 
    pb_callback_t onion_key_hash; 
    pb_callback_t path; 
    uint64_t fee; 
    pb_callback_t signature; 
    pb_callback_t block_hash; 
} helium_blockchain_txn_poc_receipts_v2;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define helium_blockchain_txn_poc_receipts_v2_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define helium_blockchain_txn_poc_receipts_v2_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define helium_blockchain_txn_poc_receipts_v2_challenger_tag 1
#define helium_blockchain_txn_poc_receipts_v2_secret_tag 2
#define helium_blockchain_txn_poc_receipts_v2_onion_key_hash_tag 3
#define helium_blockchain_txn_poc_receipts_v2_path_tag 4
#define helium_blockchain_txn_poc_receipts_v2_fee_tag 5
#define helium_blockchain_txn_poc_receipts_v2_signature_tag 6
#define helium_blockchain_txn_poc_receipts_v2_block_hash_tag 7

/* Struct field encoding specification for nanopb */
#define helium_blockchain_txn_poc_receipts_v2_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    challenger,        1) \
X(a, CALLBACK, SINGULAR, BYTES,    secret,            2) \
X(a, CALLBACK, SINGULAR, BYTES,    onion_key_hash,    3) \
X(a, CALLBACK, REPEATED, MESSAGE,  path,              4) \
X(a, STATIC,   SINGULAR, UINT64,   fee,               5) \
X(a, CALLBACK, SINGULAR, BYTES,    signature,         6) \
X(a, CALLBACK, SINGULAR, BYTES,    block_hash,        7)
#define helium_blockchain_txn_poc_receipts_v2_CALLBACK pb_default_field_callback
#define helium_blockchain_txn_poc_receipts_v2_DEFAULT NULL
#define helium_blockchain_txn_poc_receipts_v2_path_MSGTYPE helium_blockchain_poc_path_element_v1

extern const pb_msgdesc_t helium_blockchain_txn_poc_receipts_v2_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define helium_blockchain_txn_poc_receipts_v2_fields &helium_blockchain_txn_poc_receipts_v2_msg

/* Maximum encoded size of messages (where known) */
/* helium_blockchain_txn_poc_receipts_v2_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
