/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "blockchain_txn_transfer_validator_stake_v1.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(helium_blockchain_txn_transfer_validator_stake_v1, helium_blockchain_txn_transfer_validator_stake_v1, AUTO)



