/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_HELIUM_BLOCKCHAIN_TXN_PAYMENT_V2_PB_H_INCLUDED
#define PB_HELIUM_BLOCKCHAIN_TXN_PAYMENT_V2_PB_H_INCLUDED
#include <pb.h>
#include "blockchain_token_type_v1.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _helium_blockchain_txn_payment_v2 { 
    pb_callback_t payer; 
    pb_callback_t payments; 
    uint64_t fee; 
    uint64_t nonce; 
    pb_callback_t signature; 
} helium_blockchain_txn_payment_v2;

typedef struct _helium_payment { 
    pb_callback_t payee; 
    uint64_t amount; 
    uint64_t memo; 
    bool max; 
    helium_blockchain_token_type_v1 token_type; 
} helium_payment;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define helium_blockchain_txn_payment_v2_init_default {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}}
#define helium_payment_init_default              {{{NULL}, NULL}, 0, 0, 0, _helium_blockchain_token_type_v1_MIN}
#define helium_blockchain_txn_payment_v2_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}}
#define helium_payment_init_zero                 {{{NULL}, NULL}, 0, 0, 0, _helium_blockchain_token_type_v1_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define helium_blockchain_txn_payment_v2_payer_tag 1
#define helium_blockchain_txn_payment_v2_payments_tag 2
#define helium_blockchain_txn_payment_v2_fee_tag 3
#define helium_blockchain_txn_payment_v2_nonce_tag 4
#define helium_blockchain_txn_payment_v2_signature_tag 5
#define helium_payment_payee_tag                 1
#define helium_payment_amount_tag                2
#define helium_payment_memo_tag                  3
#define helium_payment_max_tag                   4
#define helium_payment_token_type_tag            5

/* Struct field encoding specification for nanopb */
#define helium_blockchain_txn_payment_v2_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    payer,             1) \
X(a, CALLBACK, REPEATED, MESSAGE,  payments,          2) \
X(a, STATIC,   SINGULAR, UINT64,   fee,               3) \
X(a, STATIC,   SINGULAR, UINT64,   nonce,             4) \
X(a, CALLBACK, SINGULAR, BYTES,    signature,         5)
#define helium_blockchain_txn_payment_v2_CALLBACK pb_default_field_callback
#define helium_blockchain_txn_payment_v2_DEFAULT NULL
#define helium_blockchain_txn_payment_v2_payments_MSGTYPE helium_payment

#define helium_payment_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    payee,             1) \
X(a, STATIC,   SINGULAR, UINT64,   amount,            2) \
X(a, STATIC,   SINGULAR, UINT64,   memo,              3) \
X(a, STATIC,   SINGULAR, BOOL,     max,               4) \
X(a, STATIC,   SINGULAR, UENUM,    token_type,        5)
#define helium_payment_CALLBACK pb_default_field_callback
#define helium_payment_DEFAULT NULL

extern const pb_msgdesc_t helium_blockchain_txn_payment_v2_msg;
extern const pb_msgdesc_t helium_payment_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define helium_blockchain_txn_payment_v2_fields &helium_blockchain_txn_payment_v2_msg
#define helium_payment_fields &helium_payment_msg

/* Maximum encoded size of messages (where known) */
/* helium_blockchain_txn_payment_v2_size depends on runtime parameters */
/* helium_payment_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
