/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_HELIUM_BLOCKCHAIN_TOKEN_TYPE_V1_PB_H_INCLUDED
#define PB_HELIUM_BLOCKCHAIN_TOKEN_TYPE_V1_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _helium_blockchain_token_type_v1 { 
    helium_blockchain_token_type_v1_hnt = 0, 
    helium_blockchain_token_type_v1_hst = 1, 
    helium_blockchain_token_type_v1_mobile = 2, 
    helium_blockchain_token_type_v1_iot = 3 
} helium_blockchain_token_type_v1;

/* Helper constants for enums */
#define _helium_blockchain_token_type_v1_MIN helium_blockchain_token_type_v1_hnt
#define _helium_blockchain_token_type_v1_MAX helium_blockchain_token_type_v1_iot
#define _helium_blockchain_token_type_v1_ARRAYSIZE ((helium_blockchain_token_type_v1)(helium_blockchain_token_type_v1_iot+1))


#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
