/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_HELIUM_BLOCKCHAIN_TXN_OUI_V1_PB_H_INCLUDED
#define PB_HELIUM_BLOCKCHAIN_TXN_OUI_V1_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _helium_blockchain_txn_oui_v1 { 
    pb_callback_t owner; 
    pb_callback_t addresses; 
    pb_callback_t filter; 
    uint32_t requested_subnet_size; 
    pb_callback_t payer; 
    uint64_t staking_fee; 
    uint64_t fee; 
    pb_callback_t owner_signature; 
    pb_callback_t payer_signature; 
    uint64_t oui; 
} helium_blockchain_txn_oui_v1;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define helium_blockchain_txn_oui_v1_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define helium_blockchain_txn_oui_v1_init_zero   {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define helium_blockchain_txn_oui_v1_owner_tag   1
#define helium_blockchain_txn_oui_v1_addresses_tag 2
#define helium_blockchain_txn_oui_v1_filter_tag  3
#define helium_blockchain_txn_oui_v1_requested_subnet_size_tag 4
#define helium_blockchain_txn_oui_v1_payer_tag   5
#define helium_blockchain_txn_oui_v1_staking_fee_tag 6
#define helium_blockchain_txn_oui_v1_fee_tag     7
#define helium_blockchain_txn_oui_v1_owner_signature_tag 8
#define helium_blockchain_txn_oui_v1_payer_signature_tag 9
#define helium_blockchain_txn_oui_v1_oui_tag     10

/* Struct field encoding specification for nanopb */
#define helium_blockchain_txn_oui_v1_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    owner,             1) \
X(a, CALLBACK, REPEATED, BYTES,    addresses,         2) \
X(a, CALLBACK, SINGULAR, BYTES,    filter,            3) \
X(a, STATIC,   SINGULAR, UINT32,   requested_subnet_size,   4) \
X(a, CALLBACK, SINGULAR, BYTES,    payer,             5) \
X(a, STATIC,   SINGULAR, UINT64,   staking_fee,       6) \
X(a, STATIC,   SINGULAR, UINT64,   fee,               7) \
X(a, CALLBACK, SINGULAR, BYTES,    owner_signature,   8) \
X(a, CALLBACK, SINGULAR, BYTES,    payer_signature,   9) \
X(a, STATIC,   SINGULAR, UINT64,   oui,              10)
#define helium_blockchain_txn_oui_v1_CALLBACK pb_default_field_callback
#define helium_blockchain_txn_oui_v1_DEFAULT NULL

extern const pb_msgdesc_t helium_blockchain_txn_oui_v1_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define helium_blockchain_txn_oui_v1_fields &helium_blockchain_txn_oui_v1_msg

/* Maximum encoded size of messages (where known) */
/* helium_blockchain_txn_oui_v1_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
