/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "blockchain_region_param_v1.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(helium_blockchain_region_params_v1, helium_blockchain_region_params_v1, AUTO)


PB_BIND(helium_tagged_spreading, helium_tagged_spreading, AUTO)


PB_BIND(helium_blockchain_region_spreading_v1, helium_blockchain_region_spreading_v1, AUTO)


PB_BIND(helium_blockchain_region_param_v1, helium_blockchain_region_param_v1, AUTO)




