/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "blockchain_snapshot_handler.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(blockchain_snapshot_req, blockchain_snapshot_req, AUTO)


PB_BIND(blockchain_snapshot_resp, blockchain_snapshot_resp, AUTO)



