/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_BLOCKCHAIN_SYNC_HANDLER_PB_H_INCLUDED
#define PB_BLOCKCHAIN_SYNC_HANDLER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _blockchain_sync_hash { 
    pb_callback_t hash; 
    pb_callback_t heights; 
} blockchain_sync_hash;

typedef struct _blockchain_sync_blocks { 
    pb_callback_t blocks; 
    bool final; 
} blockchain_sync_blocks;

typedef struct _blockchain_sync_req { 
    pb_size_t which_msg;
    union {
        blockchain_sync_hash hash;
        bool response;
    } msg; 
} blockchain_sync_req;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define blockchain_sync_hash_init_default        {{{NULL}, NULL}, {{NULL}, NULL}}
#define blockchain_sync_blocks_init_default      {{{NULL}, NULL}, 0}
#define blockchain_sync_req_init_default         {0, {blockchain_sync_hash_init_default}}
#define blockchain_sync_hash_init_zero           {{{NULL}, NULL}, {{NULL}, NULL}}
#define blockchain_sync_blocks_init_zero         {{{NULL}, NULL}, 0}
#define blockchain_sync_req_init_zero            {0, {blockchain_sync_hash_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define blockchain_sync_hash_hash_tag            1
#define blockchain_sync_hash_heights_tag         2
#define blockchain_sync_blocks_blocks_tag        1
#define blockchain_sync_blocks_final_tag         2
#define blockchain_sync_req_hash_tag             1
#define blockchain_sync_req_response_tag         2

/* Struct field encoding specification for nanopb */
#define blockchain_sync_hash_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    hash,              1) \
X(a, CALLBACK, REPEATED, UINT64,   heights,           2)
#define blockchain_sync_hash_CALLBACK pb_default_field_callback
#define blockchain_sync_hash_DEFAULT NULL

#define blockchain_sync_blocks_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, BYTES,    blocks,            1) \
X(a, STATIC,   SINGULAR, BOOL,     final,             2)
#define blockchain_sync_blocks_CALLBACK pb_default_field_callback
#define blockchain_sync_blocks_DEFAULT NULL

#define blockchain_sync_req_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,hash,msg.hash),   1) \
X(a, STATIC,   ONEOF,    BOOL,     (msg,response,msg.response),   2)
#define blockchain_sync_req_CALLBACK NULL
#define blockchain_sync_req_DEFAULT NULL
#define blockchain_sync_req_msg_hash_MSGTYPE blockchain_sync_hash

extern const pb_msgdesc_t blockchain_sync_hash_msg;
extern const pb_msgdesc_t blockchain_sync_blocks_msg;
extern const pb_msgdesc_t blockchain_sync_req_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define blockchain_sync_hash_fields &blockchain_sync_hash_msg
#define blockchain_sync_blocks_fields &blockchain_sync_blocks_msg
#define blockchain_sync_req_fields &blockchain_sync_req_msg

/* Maximum encoded size of messages (where known) */
/* blockchain_sync_hash_size depends on runtime parameters */
/* blockchain_sync_blocks_size depends on runtime parameters */
/* blockchain_sync_req_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
