/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_HELIUM_BLOCKCHAIN_ROUTING_ADDRESS_PB_H_INCLUDED
#define PB_HELIUM_BLOCKCHAIN_ROUTING_ADDRESS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _helium_routing_address { 
    pb_callback_t pub_key; 
    pb_callback_t uri; 
} helium_routing_address;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define helium_routing_address_init_default      {{{NULL}, NULL}, {{NULL}, NULL}}
#define helium_routing_address_init_zero         {{{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define helium_routing_address_pub_key_tag       1
#define helium_routing_address_uri_tag           2

/* Struct field encoding specification for nanopb */
#define helium_routing_address_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    pub_key,           1) \
X(a, CALLBACK, SINGULAR, BYTES,    uri,               2)
#define helium_routing_address_CALLBACK pb_default_field_callback
#define helium_routing_address_DEFAULT NULL

extern const pb_msgdesc_t helium_routing_address_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define helium_routing_address_fields &helium_routing_address_msg

/* Maximum encoded size of messages (where known) */
/* helium_routing_address_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
