/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "blockchain_txn_handler.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(helium_blockchain_txn_request_v1, helium_blockchain_txn_request_v1, 2)


PB_BIND(helium_blockchain_txn_info_v1, helium_blockchain_txn_info_v1, AUTO)




