/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_HELIUM_BLOCKCHAIN_TXN_SUBNETWORK_REWARDS_V1_PB_H_INCLUDED
#define PB_HELIUM_BLOCKCHAIN_TXN_SUBNETWORK_REWARDS_V1_PB_H_INCLUDED
#include <pb.h>
#include "blockchain_token_type_v1.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _helium_blockchain_txn_subnetwork_rewards_v1 { 
    helium_blockchain_token_type_v1 token_type; 
    uint64_t start_epoch; 
    uint64_t end_epoch; 
    pb_callback_t reward_server_signature; 
    pb_callback_t rewards; 
} helium_blockchain_txn_subnetwork_rewards_v1;

typedef struct _helium_subnetwork_reward { 
    pb_callback_t account; 
    uint64_t amount; 
} helium_subnetwork_reward;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define helium_subnetwork_reward_init_default    {{{NULL}, NULL}, 0}
#define helium_blockchain_txn_subnetwork_rewards_v1_init_default {_helium_blockchain_token_type_v1_MIN, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define helium_subnetwork_reward_init_zero       {{{NULL}, NULL}, 0}
#define helium_blockchain_txn_subnetwork_rewards_v1_init_zero {_helium_blockchain_token_type_v1_MIN, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define helium_blockchain_txn_subnetwork_rewards_v1_token_type_tag 1
#define helium_blockchain_txn_subnetwork_rewards_v1_start_epoch_tag 2
#define helium_blockchain_txn_subnetwork_rewards_v1_end_epoch_tag 3
#define helium_blockchain_txn_subnetwork_rewards_v1_reward_server_signature_tag 4
#define helium_blockchain_txn_subnetwork_rewards_v1_rewards_tag 5
#define helium_subnetwork_reward_account_tag     1
#define helium_subnetwork_reward_amount_tag      2

/* Struct field encoding specification for nanopb */
#define helium_subnetwork_reward_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    account,           1) \
X(a, STATIC,   SINGULAR, UINT64,   amount,            2)
#define helium_subnetwork_reward_CALLBACK pb_default_field_callback
#define helium_subnetwork_reward_DEFAULT NULL

#define helium_blockchain_txn_subnetwork_rewards_v1_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    token_type,        1) \
X(a, STATIC,   SINGULAR, UINT64,   start_epoch,       2) \
X(a, STATIC,   SINGULAR, UINT64,   end_epoch,         3) \
X(a, CALLBACK, SINGULAR, BYTES,    reward_server_signature,   4) \
X(a, CALLBACK, REPEATED, MESSAGE,  rewards,           5)
#define helium_blockchain_txn_subnetwork_rewards_v1_CALLBACK pb_default_field_callback
#define helium_blockchain_txn_subnetwork_rewards_v1_DEFAULT NULL
#define helium_blockchain_txn_subnetwork_rewards_v1_rewards_MSGTYPE helium_subnetwork_reward

extern const pb_msgdesc_t helium_subnetwork_reward_msg;
extern const pb_msgdesc_t helium_blockchain_txn_subnetwork_rewards_v1_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define helium_subnetwork_reward_fields &helium_subnetwork_reward_msg
#define helium_blockchain_txn_subnetwork_rewards_v1_fields &helium_blockchain_txn_subnetwork_rewards_v1_msg

/* Maximum encoded size of messages (where known) */
/* helium_subnetwork_reward_size depends on runtime parameters */
/* helium_blockchain_txn_subnetwork_rewards_v1_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
