/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_HELIUM_DISCOVERY_PB_H_INCLUDED
#define PB_HELIUM_DISCOVERY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _helium_discovery_start { 
    pb_callback_t hotspot; 
    pb_callback_t packets; 
    pb_callback_t signature; 
} helium_discovery_start;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define helium_discovery_start_init_default      {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define helium_discovery_start_init_zero         {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define helium_discovery_start_hotspot_tag       1
#define helium_discovery_start_packets_tag       2
#define helium_discovery_start_signature_tag     3

/* Struct field encoding specification for nanopb */
#define helium_discovery_start_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    hotspot,           1) \
X(a, CALLBACK, REPEATED, BYTES,    packets,           2) \
X(a, CALLBACK, SINGULAR, BYTES,    signature,         3)
#define helium_discovery_start_CALLBACK pb_default_field_callback
#define helium_discovery_start_DEFAULT NULL

extern const pb_msgdesc_t helium_discovery_start_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define helium_discovery_start_fields &helium_discovery_start_msg

/* Maximum encoded size of messages (where known) */
/* helium_discovery_start_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
