/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "longfi.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(helium_longfi_LongFiReq, helium_longfi_LongFiReq, AUTO)


PB_BIND(helium_longfi_LongFiResp, helium_longfi_LongFiResp, AUTO)


PB_BIND(helium_longfi_LongFiTxStatus, helium_longfi_LongFiTxStatus, AUTO)


PB_BIND(helium_longfi_LongFiRxPacket, helium_longfi_LongFiRxPacket, AUTO)


PB_BIND(helium_longfi_LongFiTxPacket, helium_longfi_LongFiTxPacket, AUTO)




