/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "radio.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(helium_radio_RadioReq, helium_radio_RadioReq, AUTO)


PB_BIND(helium_radio_RadioResp, helium_radio_RadioResp, AUTO)


PB_BIND(helium_radio_RadioTxReq, helium_radio_RadioTxReq, AUTO)


PB_BIND(helium_radio_RadioRxPacket, helium_radio_RadioRxPacket, AUTO)


PB_BIND(helium_radio_RadioTxResp, helium_radio_RadioTxResp, AUTO)







