/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_HELIUM_REGION_PB_H_INCLUDED
#define PB_HELIUM_REGION_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _helium_region { 
    helium_region_US915 = 0, 
    helium_region_EU868 = 1, 
    helium_region_EU433 = 2, 
    helium_region_CN470 = 3, 
    /* CN779 is deprecated. */
    helium_region_CN779 = 4, 
    helium_region_AU915 = 5, 
    helium_region_AS923_1 = 6, 
    helium_region_KR920 = 7, 
    helium_region_IN865 = 8, 
    helium_region_AS923_2 = 9, 
    helium_region_AS923_3 = 10, 
    helium_region_AS923_4 = 11, 
    helium_region_AS923_1B = 12, 
    helium_region_CD900_1A = 13 
} helium_region;

/* Helper constants for enums */
#define _helium_region_MIN helium_region_US915
#define _helium_region_MAX helium_region_CD900_1A
#define _helium_region_ARRAYSIZE ((helium_region)(helium_region_CD900_1A+1))


#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
