/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev */

#ifndef PB_STATE_CHANNEL_V1_PB_H_INCLUDED
#define PB_STATE_CHANNEL_V1_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _state_channel_packet_v1 {
    pb_callback_t packet;
    pb_callback_t signature;
/* @@protoc_insertion_point(struct:state_channel_packet_v1) */
} state_channel_packet_v1;


typedef struct _state_channel_request_v1 {
    pb_callback_t payee;
    uint64_t amount;
    uint32_t fingerprint;
/* @@protoc_insertion_point(struct:state_channel_request_v1) */
} state_channel_request_v1;


typedef struct _state_channel_v1 {
    pb_callback_t id;
    pb_callback_t owner;
    uint64_t credits;
    uint64_t nonce;
    pb_callback_t balances;
    pb_callback_t packets;
    pb_callback_t signature;
/* @@protoc_insertion_point(struct:state_channel_v1) */
} state_channel_v1;


typedef struct _state_channel_v1_BalancesEntry {
    pb_callback_t key;
    uint64_t value;
/* @@protoc_insertion_point(struct:state_channel_v1_BalancesEntry) */
} state_channel_v1_BalancesEntry;


typedef struct _state_channel_message_v1 {
    pb_size_t which_msg;
    union {
        state_channel_request_v1 request;
        state_channel_v1 state_channel;
        state_channel_packet_v1 packet;
    } msg;
/* @@protoc_insertion_point(struct:state_channel_message_v1) */
} state_channel_message_v1;


/* Initializer values for message structs */
#define state_channel_request_v1_init_default    {{{NULL}, NULL}, 0, 0}
#define state_channel_v1_init_default            {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define state_channel_v1_BalancesEntry_init_default {{{NULL}, NULL}, 0}
#define state_channel_packet_v1_init_default     {{{NULL}, NULL}, {{NULL}, NULL}}
#define state_channel_message_v1_init_default    {0, {state_channel_request_v1_init_default}}
#define state_channel_request_v1_init_zero       {{{NULL}, NULL}, 0, 0}
#define state_channel_v1_init_zero               {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define state_channel_v1_BalancesEntry_init_zero {{{NULL}, NULL}, 0}
#define state_channel_packet_v1_init_zero        {{{NULL}, NULL}, {{NULL}, NULL}}
#define state_channel_message_v1_init_zero       {0, {state_channel_request_v1_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define state_channel_packet_v1_packet_tag       1
#define state_channel_packet_v1_signature_tag    2
#define state_channel_request_v1_payee_tag       1
#define state_channel_request_v1_amount_tag      2
#define state_channel_request_v1_fingerprint_tag 3
#define state_channel_v1_id_tag                  1
#define state_channel_v1_owner_tag               2
#define state_channel_v1_credits_tag             3
#define state_channel_v1_nonce_tag               4
#define state_channel_v1_balances_tag            5
#define state_channel_v1_packets_tag             6
#define state_channel_v1_signature_tag           7
#define state_channel_v1_BalancesEntry_key_tag   1
#define state_channel_v1_BalancesEntry_value_tag 2
#define state_channel_message_v1_request_tag     1
#define state_channel_message_v1_state_channel_tag 2
#define state_channel_message_v1_packet_tag      3

/* Struct field encoding specification for nanopb */
#define state_channel_request_v1_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES, payee, 1) \
X(a, STATIC, SINGULAR, UINT64, amount, 2) \
X(a, STATIC, SINGULAR, UINT32, fingerprint, 3)
#define state_channel_request_v1_CALLBACK pb_default_field_callback
#define state_channel_request_v1_DEFAULT NULL

#define state_channel_v1_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES, id, 1) \
X(a, CALLBACK, SINGULAR, BYTES, owner, 2) \
X(a, STATIC, SINGULAR, UINT64, credits, 3) \
X(a, STATIC, SINGULAR, UINT64, nonce, 4) \
X(a, CALLBACK, REPEATED, MESSAGE, balances, 5) \
X(a, CALLBACK, SINGULAR, BYTES, packets, 6) \
X(a, CALLBACK, SINGULAR, BYTES, signature, 7)
#define state_channel_v1_CALLBACK pb_default_field_callback
#define state_channel_v1_DEFAULT NULL
#define state_channel_v1_balances_MSGTYPE state_channel_v1_BalancesEntry

#define state_channel_v1_BalancesEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING, key, 1) \
X(a, STATIC, SINGULAR, UINT64, value, 2)
#define state_channel_v1_BalancesEntry_CALLBACK pb_default_field_callback
#define state_channel_v1_BalancesEntry_DEFAULT NULL

#define state_channel_packet_v1_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES, packet, 1) \
X(a, CALLBACK, SINGULAR, BYTES, signature, 2)
#define state_channel_packet_v1_CALLBACK pb_default_field_callback
#define state_channel_packet_v1_DEFAULT NULL

#define state_channel_message_v1_FIELDLIST(X, a) \
X(a, STATIC, ONEOF, MESSAGE, (msg,request,msg.request), 1) \
X(a, STATIC, ONEOF, MESSAGE, (msg,state_channel,msg.state_channel), 2) \
X(a, STATIC, ONEOF, MESSAGE, (msg,packet,msg.packet), 3)
#define state_channel_message_v1_CALLBACK NULL
#define state_channel_message_v1_DEFAULT NULL
#define state_channel_message_v1_msg_request_MSGTYPE state_channel_request_v1
#define state_channel_message_v1_msg_state_channel_MSGTYPE state_channel_v1
#define state_channel_message_v1_msg_packet_MSGTYPE state_channel_packet_v1

extern const pb_msgdesc_t state_channel_request_v1_msg;
extern const pb_msgdesc_t state_channel_v1_msg;
extern const pb_msgdesc_t state_channel_v1_BalancesEntry_msg;
extern const pb_msgdesc_t state_channel_packet_v1_msg;
extern const pb_msgdesc_t state_channel_message_v1_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define state_channel_request_v1_fields &state_channel_request_v1_msg
#define state_channel_v1_fields &state_channel_v1_msg
#define state_channel_v1_BalancesEntry_fields &state_channel_v1_BalancesEntry_msg
#define state_channel_packet_v1_fields &state_channel_packet_v1_msg
#define state_channel_message_v1_fields &state_channel_message_v1_msg

/* Maximum encoded size of messages (where known) */
/* state_channel_request_v1_size depends on runtime parameters */
/* state_channel_v1_size depends on runtime parameters */
/* state_channel_v1_BalancesEntry_size depends on runtime parameters */
/* state_channel_packet_v1_size depends on runtime parameters */
/* state_channel_message_v1_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
