/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev */

#include "state_channel_v1.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(state_channel_request_v1, state_channel_request_v1, AUTO)


PB_BIND(state_channel_v1, state_channel_v1, AUTO)


PB_BIND(state_channel_v1_BalancesEntry, state_channel_v1_BalancesEntry, AUTO)


PB_BIND(state_channel_packet_v1, state_channel_packet_v1, AUTO)


PB_BIND(state_channel_message_v1, state_channel_message_v1, AUTO)



/* @@protoc_insertion_point(eof) */
