/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_HELIUM_BLOCKCHAIN_TXN_REWARDS_V2_PB_H_INCLUDED
#define PB_HELIUM_BLOCKCHAIN_TXN_REWARDS_V2_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _helium_blockchain_txn_reward_v2 { 
    pb_callback_t account; 
    uint64_t amount; 
} helium_blockchain_txn_reward_v2;

typedef struct _helium_blockchain_txn_rewards_v2 { 
    uint64_t start_epoch; 
    uint64_t end_epoch; 
    pb_callback_t rewards; 
} helium_blockchain_txn_rewards_v2;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define helium_blockchain_txn_reward_v2_init_default {{{NULL}, NULL}, 0}
#define helium_blockchain_txn_rewards_v2_init_default {0, 0, {{NULL}, NULL}}
#define helium_blockchain_txn_reward_v2_init_zero {{{NULL}, NULL}, 0}
#define helium_blockchain_txn_rewards_v2_init_zero {0, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define helium_blockchain_txn_reward_v2_account_tag 1
#define helium_blockchain_txn_reward_v2_amount_tag 2
#define helium_blockchain_txn_rewards_v2_start_epoch_tag 1
#define helium_blockchain_txn_rewards_v2_end_epoch_tag 2
#define helium_blockchain_txn_rewards_v2_rewards_tag 3

/* Struct field encoding specification for nanopb */
#define helium_blockchain_txn_reward_v2_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    account,           1) \
X(a, STATIC,   SINGULAR, UINT64,   amount,            2)
#define helium_blockchain_txn_reward_v2_CALLBACK pb_default_field_callback
#define helium_blockchain_txn_reward_v2_DEFAULT NULL

#define helium_blockchain_txn_rewards_v2_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   start_epoch,       1) \
X(a, STATIC,   SINGULAR, UINT64,   end_epoch,         2) \
X(a, CALLBACK, REPEATED, MESSAGE,  rewards,           3)
#define helium_blockchain_txn_rewards_v2_CALLBACK pb_default_field_callback
#define helium_blockchain_txn_rewards_v2_DEFAULT NULL
#define helium_blockchain_txn_rewards_v2_rewards_MSGTYPE helium_blockchain_txn_reward_v2

extern const pb_msgdesc_t helium_blockchain_txn_reward_v2_msg;
extern const pb_msgdesc_t helium_blockchain_txn_rewards_v2_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define helium_blockchain_txn_reward_v2_fields &helium_blockchain_txn_reward_v2_msg
#define helium_blockchain_txn_rewards_v2_fields &helium_blockchain_txn_rewards_v2_msg

/* Maximum encoded size of messages (where known) */
/* helium_blockchain_txn_reward_v2_size depends on runtime parameters */
/* helium_blockchain_txn_rewards_v2_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
