/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_HELIUM_BLOCKCHAIN_TXN_STATE_CHANNEL_CLOSE_V1_PB_H_INCLUDED
#define PB_HELIUM_BLOCKCHAIN_TXN_STATE_CHANNEL_CLOSE_V1_PB_H_INCLUDED
#include <pb.h>
#include "blockchain_state_channel_v1.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _helium_blockchain_txn_state_channel_close_v1 { 
    bool has_state_channel;
    helium_blockchain_state_channel_v1 state_channel; 
    pb_callback_t closer; 
    pb_callback_t signature; 
    uint64_t fee; 
    bool has_conflicts_with;
    helium_blockchain_state_channel_v1 conflicts_with; 
} helium_blockchain_txn_state_channel_close_v1;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define helium_blockchain_txn_state_channel_close_v1_init_default {false, helium_blockchain_state_channel_v1_init_default, {{NULL}, NULL}, {{NULL}, NULL}, 0, false, helium_blockchain_state_channel_v1_init_default}
#define helium_blockchain_txn_state_channel_close_v1_init_zero {false, helium_blockchain_state_channel_v1_init_zero, {{NULL}, NULL}, {{NULL}, NULL}, 0, false, helium_blockchain_state_channel_v1_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define helium_blockchain_txn_state_channel_close_v1_state_channel_tag 1
#define helium_blockchain_txn_state_channel_close_v1_closer_tag 2
#define helium_blockchain_txn_state_channel_close_v1_signature_tag 3
#define helium_blockchain_txn_state_channel_close_v1_fee_tag 4
#define helium_blockchain_txn_state_channel_close_v1_conflicts_with_tag 5

/* Struct field encoding specification for nanopb */
#define helium_blockchain_txn_state_channel_close_v1_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  state_channel,     1) \
X(a, CALLBACK, SINGULAR, BYTES,    closer,            2) \
X(a, CALLBACK, SINGULAR, BYTES,    signature,         3) \
X(a, STATIC,   SINGULAR, UINT64,   fee,               4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  conflicts_with,    5)
#define helium_blockchain_txn_state_channel_close_v1_CALLBACK pb_default_field_callback
#define helium_blockchain_txn_state_channel_close_v1_DEFAULT NULL
#define helium_blockchain_txn_state_channel_close_v1_state_channel_MSGTYPE helium_blockchain_state_channel_v1
#define helium_blockchain_txn_state_channel_close_v1_conflicts_with_MSGTYPE helium_blockchain_state_channel_v1

extern const pb_msgdesc_t helium_blockchain_txn_state_channel_close_v1_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define helium_blockchain_txn_state_channel_close_v1_fields &helium_blockchain_txn_state_channel_close_v1_msg

/* Maximum encoded size of messages (where known) */
/* helium_blockchain_txn_state_channel_close_v1_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
