/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "blockchain_txn_poc_receipts_v1.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(helium_blockchain_poc_receipt_v1, helium_blockchain_poc_receipt_v1, AUTO)


PB_BIND(helium_blockchain_poc_witness_v1, helium_blockchain_poc_witness_v1, AUTO)


PB_BIND(helium_blockchain_poc_response_v1, helium_blockchain_poc_response_v1, AUTO)


PB_BIND(helium_blockchain_poc_path_element_v1, helium_blockchain_poc_path_element_v1, AUTO)


PB_BIND(helium_blockchain_txn_poc_receipts_v1, helium_blockchain_txn_poc_receipts_v1, AUTO)




