/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "blockchain_gossip_handler.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(blockchain_gossip_block, blockchain_gossip_block, AUTO)



