/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_HELIUM_BLOCKCHAIN_TXN_UPDATE_GATEWAY_OUI_V1_PB_H_INCLUDED
#define PB_HELIUM_BLOCKCHAIN_TXN_UPDATE_GATEWAY_OUI_V1_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _helium_blockchain_txn_update_gateway_oui_v1 { 
    pb_callback_t gateway; 
    uint64_t oui; 
    uint64_t nonce; 
    uint64_t fee; 
    pb_callback_t gateway_owner_signature; 
    pb_callback_t oui_owner_signature; 
} helium_blockchain_txn_update_gateway_oui_v1;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define helium_blockchain_txn_update_gateway_oui_v1_init_default {{{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define helium_blockchain_txn_update_gateway_oui_v1_init_zero {{{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define helium_blockchain_txn_update_gateway_oui_v1_gateway_tag 1
#define helium_blockchain_txn_update_gateway_oui_v1_oui_tag 2
#define helium_blockchain_txn_update_gateway_oui_v1_nonce_tag 3
#define helium_blockchain_txn_update_gateway_oui_v1_fee_tag 4
#define helium_blockchain_txn_update_gateway_oui_v1_gateway_owner_signature_tag 5
#define helium_blockchain_txn_update_gateway_oui_v1_oui_owner_signature_tag 6

/* Struct field encoding specification for nanopb */
#define helium_blockchain_txn_update_gateway_oui_v1_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    gateway,           1) \
X(a, STATIC,   SINGULAR, UINT64,   oui,               2) \
X(a, STATIC,   SINGULAR, UINT64,   nonce,             3) \
X(a, STATIC,   SINGULAR, UINT64,   fee,               4) \
X(a, CALLBACK, SINGULAR, BYTES,    gateway_owner_signature,   5) \
X(a, CALLBACK, SINGULAR, BYTES,    oui_owner_signature,   6)
#define helium_blockchain_txn_update_gateway_oui_v1_CALLBACK pb_default_field_callback
#define helium_blockchain_txn_update_gateway_oui_v1_DEFAULT NULL

extern const pb_msgdesc_t helium_blockchain_txn_update_gateway_oui_v1_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define helium_blockchain_txn_update_gateway_oui_v1_fields &helium_blockchain_txn_update_gateway_oui_v1_msg

/* Maximum encoded size of messages (where known) */
/* helium_blockchain_txn_update_gateway_oui_v1_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
