/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_HELIUM_BLOCKCHAIN_TXN_GEN_PRICE_ORACLE_V1_PB_H_INCLUDED
#define PB_HELIUM_BLOCKCHAIN_TXN_GEN_PRICE_ORACLE_V1_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _helium_blockchain_txn_gen_price_oracle_v1 { 
    uint64_t price; 
} helium_blockchain_txn_gen_price_oracle_v1;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define helium_blockchain_txn_gen_price_oracle_v1_init_default {0}
#define helium_blockchain_txn_gen_price_oracle_v1_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */
#define helium_blockchain_txn_gen_price_oracle_v1_price_tag 1

/* Struct field encoding specification for nanopb */
#define helium_blockchain_txn_gen_price_oracle_v1_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   price,             1)
#define helium_blockchain_txn_gen_price_oracle_v1_CALLBACK NULL
#define helium_blockchain_txn_gen_price_oracle_v1_DEFAULT NULL

extern const pb_msgdesc_t helium_blockchain_txn_gen_price_oracle_v1_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define helium_blockchain_txn_gen_price_oracle_v1_fields &helium_blockchain_txn_gen_price_oracle_v1_msg

/* Maximum encoded size of messages (where known) */
#define helium_blockchain_txn_gen_price_oracle_v1_size 11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
