/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "packet.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(helium_eui, helium_eui, AUTO)


PB_BIND(helium_routing_information, helium_routing_information, AUTO)


PB_BIND(helium_window, helium_window, AUTO)


PB_BIND(helium_packet, helium_packet, AUTO)




