name: CI

on:
  push:
    branches: [master]
    tags: ["v*"]
  pull_request:
    branches: [master]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      working-directory: ./companion-app
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
          components: clippy, rustfmt

      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - name: Check formatting
        run: cargo fmt  -- --check
        working-directory: ${{env.working-directory}}

      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -Dclippy::all
        working-directory: ${{env.working-directory}}

      - name: Build
        run: cargo build --all --release
        working-directory: ${{env.working-directory}}

      - name: Name Release
        if: startsWith(github.ref, 'refs/tags/')
        id: name_release
        run: echo ::set-output name=RELEASE::helium-ledger-app-$(echo $GITHUB_REF | cut -d / -f 3)-x86-64-linux

      - name: Prepare Release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NAME: ${{ steps.name_release.outputs.RELEASE }}
        working-directory: ${{env.working-directory}}
        run: |
          mkdir $NAME
          mv target/release/helium-ledger-app $NAME/
          cp README.md $NAME/
          cp LICENSE $NAME/
          tar -zcvf $NAME.tar.gz $NAME/
      - name: Push Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        working-directory: ${{env.working-directory}}
        with:
          files: |
            ${{ steps.name_release.outputs.RELEASE }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-mac:
    runs-on: macos-latest
    env:
      working-directory: ./companion-app
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          default: true
          override: true

      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - name: Build
        run: cargo build --all --release
        working-directory: ${{env.working-directory}}

      - name: Name Release
        if: startsWith(github.ref, 'refs/tags/')
        id: name_release
        run: echo ::set-output name=RELEASE::helium-ledger-app-$(echo $GITHUB_REF | cut -d / -f 3)-x86-64-macos

      - name: Prepare Release
        if: startsWith(github.ref, 'refs/tags/')
        working-directory: ${{env.working-directory}}
        env:
          NAME: ${{ steps.name_release.outputs.RELEASE }}
        run: |
          mkdir $NAME
          mv target/release/helium-ledger-app $NAME/
          cp README.md $NAME/
          cp LICENSE $NAME/
          tar -zcvf $NAME.tar.gz $NAME/
      - name: Push Release
        working-directory: ${{env.working-directory}}
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ steps.name_release.outputs.RELEASE }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest
    env:
      working-directory: ./companion-app
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
          default: true
          override: true

      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - name: Build
        run: cargo build --all --release
        working-directory: ${{env.working-directory}}

      - name: Name Release
        if: startsWith(github.ref, 'refs/tags/')
        working-directory: ${{env.working-directory}}
        id: name_release
        run: echo ::set-output name=RELEASE::helium-ledger-app-$(echo $GITHUB_REF | cut -d / -f 3)-x86-64-win

      - name: Prepare Release
        if: startsWith(github.ref, 'refs/tags/')
        working-directory: ${{env.working-directory}}
        env:
          NAME: ${{ steps.name_release.outputs.RELEASE }}
        run: |
          mkdir $NAME
          mv target/release/helium-ledger-app $NAME/
          cp README.md $NAME/
          cp LICENSE $NAME/
          tar -zcvf $NAME.tar.gz $NAME/
      - name: Push Release
        uses: softprops/action-gh-release@v1
        working-directory: ${{env.working-directory}}
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ steps.name_release.outputs.RELEASE }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

